CREATE SCHEMA IF NOT EXISTS arkad;

GRANT USAGE, CREATE ON SCHEMA arkad TO arkazilla;

ALTER DEFAULT PRIVILEGES IN SCHEMA arkad GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO arkazilla;
ALTER DEFAULT PRIVILEGES IN SCHEMA arkad GRANT USAGE ON SEQUENCES TO arkazilla;

