// <auto-generated />
using System;
using ArkaZilla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArkaZilla.Data.Migrations
{
    [DbContext(typeof(ArkaZillaDbContext))]
    [Migration("20251215073237_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("arkad")
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArkaZilla.Data.Models.Logging.DefaultLoggingsForCategories", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("CategoryId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("LoggingId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("LoggingId");

                    b.ToTable("DefaultLoggingsForCategories", "arkad");
                });

            modelBuilder.Entity("ArkaZilla.Data.Models.Logging.DefaultLoggingsForServers", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("LoggingId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("LoggingId");

                    b.ToTable("DefaultLoggingsForServers", "arkad");
                });

            modelBuilder.Entity("ArkaZilla.Data.Models.Logging.LogLocation", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("IdentifierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("LoggingId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("LoggingId");

                    b.ToTable("LogLocations", "arkad");
                });

            modelBuilder.Entity("ArkaZilla.Data.Models.Logging.Logging", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("CallName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Loggings", "arkad");
                });

            modelBuilder.Entity("ArkaZilla.Data.Models.User", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("DiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("HasConsented")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("IdentityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", "arkad");
                });

            modelBuilder.Entity("ArkaZilla.Data.Models.Logging.DefaultLoggingsForCategories", b =>
                {
                    b.HasOne("ArkaZilla.Data.Models.Logging.Logging", "Logging")
                        .WithMany()
                        .HasForeignKey("LoggingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logging");
                });

            modelBuilder.Entity("ArkaZilla.Data.Models.Logging.DefaultLoggingsForServers", b =>
                {
                    b.HasOne("ArkaZilla.Data.Models.Logging.Logging", "Logging")
                        .WithMany()
                        .HasForeignKey("LoggingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logging");
                });

            modelBuilder.Entity("ArkaZilla.Data.Models.Logging.LogLocation", b =>
                {
                    b.HasOne("ArkaZilla.Data.Models.Logging.Logging", "Logging")
                        .WithMany()
                        .HasForeignKey("LoggingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logging");
                });
#pragma warning restore 612, 618
        }
    }
}
